### ISSUE TITLE
ZHA is "not loaded" anymore after editing configuration.yaml for zha_quirks

### ISSUE THREAD

**Issue by dhavaldesai-HA** [jacekk015/zha_quirks#75]
I'm running HA on Proxmox. After doing the installation and editing the configuration.yaml file, it breaks my ZHA instance. It shows that ZHA is "not loaded" anymore. 

My root folder is /homeassistant. 
I've created a new directory under /homeassistant and named it "custom_zha_quirks". Quirks py file is under that directory. 

** Added this under configuration.yaml **
```
# Zigbee Moes Thermostat
zha:
  database_path: /homeassistant/zigbee.db
  enable_quirks: true
  custom_quirks_path: /homeassistant/custom_zha_quirks/
```
Can someone help please as I've now lost all my previous smart devices that were working over ZHA till now. 

![image](https://github.com/user-attachments/assets/16763920-6299-45dc-a7e5-8ff0917a9ab2)

**Comment by renegade304** [comment]
It should be:
```
zha:
  custom_quirks_path: /config/custom_zha_quirks/
```

**Comment by dhavaldesai-HA** [comment]
I'm running HA on Proxmox. I don't have a 'config' directory. My root directory is called 'homeassistant/'

**Comment by dhavaldesai-HA** [comment]
I figured it out. If someone else is facing the same issue, pls use following entry in configuration.yaml file

```
# Zigbee Moes Thermostat
zha:
  enable_quirks: true
  custom_quirks_path: custom_zha_quirks/
```
